sudo: required

services:
  - docker

before_install:
  - docker build -t quangdvn/test-ci-cd -f Dockerfile.dev .

script:
  - docker run quangdvn/test-ci-cd -e CI=true yarn test

deploy:
  provider: elasticbeanstalk
  access_key_id: '$AWS_ACCESS_KEY_ID'
  secret_access_key:
    secure: '$AWS_SECRET_ACCESS_KEY'
  region: 'ap-southeast-1'
  app: 'quangdvn-docker-react'
  env: 'QuangdvnDockerReact-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-1-006923918343'
  bucket_path: 'quangdvn-docker-react'
  on:
    branch: master
